version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: officina_postgres
    environment:
      - POSTGRES_DB=officina_db
      - POSTGRES_USER=officina_user
      - POSTGRES_PASSWORD=officina_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  officina:
    image: openjdk:17-jdk-slim
    container_name: officina_app
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/officina_db
      SPRING_DATASOURCE_USERNAME: officina_user
      SPRING_DATASOURCE_PASSWORD: officina_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./target:/app
    command: java -jar /app/officina-0.0.1-SNAPSHOT.jar

volumes:
  postgres-data:  # Dichiarazione del volume
