version: '3.8'

services:
  postgres:
    image: postgres:latest  # Corretto il nome dell'immagine
    container_name: officina_postgres
    environment:
      - POSTGRES_DB=officina_db
      - POSTGRES_USER=officina_user
      - POSTGRES_PASSWORD=officina_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
